services:
  english-assistant_db:
    container_name: english-assistant_db
    image: postgres:14.3-alpine
    restart: unless-stopped
    volumes:
      - ./backend_db:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  english-assistant_api:
    container_name: english-assistant_api
    build: .
    restart: unless-stopped
    depends_on:
      english-assistant_db:
        condition: service_healthy
    volumes:
      - .:/app
      - ./static:/app/english-assistant/static
    ports:
      - 9064:80
    command: ["python", "/app/english-assistant/manage.py", "runserver", "0:80"]
    env_file:
      - .env

  english-assistant_redis:
    container_name: english-assistant_redis
    image: redis:6.2-alpine
    restart: unless-stopped

  english-assistant_ws:
    container_name: english-assistant_ws
    build: .
    restart: unless-stopped
    working_dir: /app/english-assistant
    env_file:
      - .env
    ports:
      - "127.0.0.1:9080:9080"
    command: ["uvicorn", "--reload", "--host", "0.0.0.0", "--port", "9080", "english-assistant.asgi:application", "--workers", "2"]
