services:
  english-assistant_db:
    container_name: english-assistant_db
    image: postgres:14.3-alpine
    restart: unless-stopped
    volumes:
      - ./backend_db:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 5

  english-assistant_api:
    container_name: english-assistant_api
    build: .
    restart: unless-stopped
    depends_on:
      crypto_assets_db:
        condition: service_healthy
    volumes:
      - .:/app
    ports:
      - 9064:80
    command: ["python", "/app/english-assistant/manage.py", "runserver", "0:80"]
    env_file:
      - .env
