# Generated by Django 5.1 on 2025-08-02 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ai_word_count_limit',
            field=models.PositiveIntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
