# Generated by Django 5.1 on 2025-06-07 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grammar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('content', models.TextField(help_text='Text content of the message')),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('audio', 'Audio')], default='text', help_text='Type of message (text or audio)', max_length=10)),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('ai', 'AI Assistant')], help_text='Who sent the message (user or AI)', max_length=10)),
                ('audio_file', models.FileField(blank=True, help_text='Audio file for voice messages', null=True, upload_to='chat_audio/%Y/%m/%d/')),
                ('audio_duration', models.FloatField(blank=True, help_text='Duration of audio message in seconds', null=True)),
                ('transcription', models.TextField(blank=True, help_text='Transcription of audio message', null=True)),
                ('response_id', models.CharField(blank=True, help_text='Unique identifier for AI responses', max_length=50, null=True)),
                ('session_id', models.CharField(blank=True, help_text='WebSocket session identifier', max_length=100, null=True)),
                ('user_timezone', models.CharField(default='UTC', help_text="User's timezone when message was sent", max_length=50)),
                ('thumb_up', models.IntegerField(default=0, help_text='Number of thumbs up received')),
                ('thumb_down', models.IntegerField(default=0, help_text='Number of thumbs down received')),
                ('grammar', models.ForeignKey(help_text='Grammar topic being discussed', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='grammar.grammar')),
                ('user', models.ForeignKey(help_text='User who initiated the chat session', on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'grammar', '-created_at'], name='chat_messag_user_id_30d4b0_idx'), models.Index(fields=['response_id'], name='chat_messag_respons_cf6a8c_idx'), models.Index(fields=['session_id'], name='chat_messag_session_389d44_idx'), models.Index(fields=['sender_type', '-created_at'], name='chat_messag_sender__f9f00c_idx')],
            },
        ),
    ]
